/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.bined.theme.gui;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.event.ListDataListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.exbin.framework.App;
import org.exbin.framework.bined.theme.model.ThemeProfile;
import org.exbin.framework.bined.theme.model.ThemeProfilesListModel;
import org.exbin.framework.bined.theme.settings.gui.PreviewPanel;
import org.exbin.framework.bined.theme.settings.gui.ProfileListPanel;
import org.exbin.framework.language.api.LanguageModuleApi;

/**
 * Manage list of theme templates panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class ThemeTemplatesPanel extends javax.swing.JPanel implements ProfileListPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(ThemeTemplatesPanel.class);

    protected Controller controller;

    public ThemeTemplatesPanel() {
        initComponents();
        init();
    }

    private void init() {
        templatesList.setModel(new ThemeProfilesListModel());
        templatesList.setCellRenderer(new ProfileCellRenderer());
        templatesList.addListSelectionListener((ListSelectionEvent e) -> updateStates());
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    private void updateStates() {
        ThemeProfile themeProfile = getSelectedTemplate();
        if (themeProfile != null) {
            controller.updatePreview(previewPanel, themeProfile);
        }
    }

    @Nullable
    public ThemeProfile getSelectedTemplate() {
        int selectedIndex = templatesList.getSelectedIndex();
        return selectedIndex < 0 ? null : getProfilesListModel().getElementAt(selectedIndex);
    }

    public void addListSelectionListener(ListSelectionListener listener) {
        templatesList.addListSelectionListener(listener);
    }

    @Nonnull
    @Override
    public List<String> getProfileNames() {
        List<String> profileNames = new ArrayList<>();
        getProfilesListModel().getProfiles().forEach((profile) -> profileNames.add(profile.getProfileName()));
        return profileNames;
    }

    @Nonnull
    public ThemeProfilesListModel getProfilesListModel() {
        return ((ThemeProfilesListModel) templatesList.getModel());
    }

    @Override
    public void addProfileListPanelListener(ListDataListener listener) {
        getProfilesListModel().addListDataListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilesListScrollPane = new javax.swing.JScrollPane();
        templatesList = new javax.swing.JList<>();
        previewPanel = new org.exbin.framework.bined.theme.settings.gui.PreviewPanel();

        profilesListScrollPane.setViewportView(templatesList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilesListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(profilesListScrollPane))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addProfilesListListener(ListDataListener listener) {
        getProfilesListModel().addListDataListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.exbin.framework.bined.theme.settings.gui.PreviewPanel previewPanel;
    private javax.swing.JScrollPane profilesListScrollPane;
    private javax.swing.JList<ThemeProfile> templatesList;
    // End of variables declaration//GEN-END:variables

    @ParametersAreNonnullByDefault
    private static final class ProfileCellRenderer implements ListCellRenderer<ThemeProfile> {

        private final DefaultListCellRenderer defaultListCellRenderer = new DefaultListCellRenderer();

        @Nonnull
        @Override
        public Component getListCellRendererComponent(JList<? extends ThemeProfile> list, ThemeProfile value, int index, boolean isSelected, boolean cellHasFocus) {
            return defaultListCellRenderer.getListCellRendererComponent(list, value != null ? value.getProfileName() : null, index, isSelected, cellHasFocus);
        }
    }

    @ParametersAreNonnullByDefault
    public interface Controller {

        void updatePreview(PreviewPanel previewPanel, ThemeProfile themeProfile);
    }
}
