viewRowWrappingAction.text=Row Wrapping mode
viewRowWrappingAction.shortDescription=Enable/disable cutting rows on width of the window
goToPositionAction.text=Go To
goToPositionAction.shortDescription=Move cursor to given position
viewNonprintablesAction.text=Show Nonprintables
viewNonprintablesAction.shortDescription=Show nonprintable/whitespace characters
viewNonprintablesToolbarAction.text=Nonp.
viewNonprintablesToolbarAction.shortDescription=Show nonprintable/whitespace characters
viewNonprintablesToolbarAction.smallIcon=/org/exbin/bined/jaguif/component/resources/icons/insert-pilcrow.png
zoomInAction.text=Zoom In
zoomInAction.shortDescription=Increase font size
zoomOutAction.text=Zoom Out
zoomOutAction.shortDescription=Decrease font size
resetFontSizeAction.text=Reset Font Size
resetFontSizeAction.shortDescription=Reset font size to default (12)
dualViewModeAction.text=Dual
dualViewModeAction.shortDescription=Show both code and text preview
codeMatrixViewModeAction.text=Code Matrix
codeMatrixViewModeAction.shortDescription=Show only code matrix
textPreviewViewModeAction.text=Text Preview
textPreviewViewModeAction.shortDescription=Show only text preview
copyAsCodeAction.text=Copy as Code
copyAsCodeAction.shortDescription=Copy selection to clipboard as text representing code
pasteFromCodeAction.text=Paste from Code
pasteFromCodeAction.shortDescription=Paste from clipboard from text representing code
newFileTitlePrefix=New File
viewFontSubMenu.name=Font
