dialog.title=Convert Data
header.title=Convert Data
header.description=Convert all data or selected data
header.icon=/org/exbin/bined/jaguif/operation/method/resources/icons/48px/system-run-6.png
convertButton.text=Convert
closeButton.text=Close
convertToNewFileButton.text=To New File
convertToClipboardButton.text=To Clipboard
cancelButton.text=Cancel
