selectionFromLabel.toolTipText=Selection from
selectionToLabel.toolTipText=Selection to
dataSizeLabel.toolTipText=Data size
selectionLengthLabel.toolTipText=Selection length
dataSizeCopyMenuItem.text=Copy
octDataSizeModeMenuItem.text=Show as octal
decDataSizeModeMenuItem.text=Show as decimal
hexDataSizeModeMenuItem.text=Show as hexadecimal
octDataSizeModeRadioButtonMenuItem.text=Show as octal
decDataSizeModeRadioButtonMenuItem.text=Show as decimal
hexadecimalDataSizeModeRadioButtonMenuItem.text=Show as hexadecimal
caretPosition.text=%s to %s
dataSize.text=%s of %s
codeType.octal=OCT
codeType.decimal=DEC
codeType.hexadecimal=HEX
