dialog.title=Paste From
header.title=Paste From
header.description=Paste data from clipboard parsing it from a specific form
header.icon=/org/exbin/bined/jaguif/operation/method/resources/icons/48px/edit-paste-4.png
okButton.text=Paste
cancelButton.text=Cancel
