header.title=Colors Profile Templates
header.description=Select colors template to use for editor
header.icon=/org/exbin/bined/jaguif/theme/resources/icons/48px/colorize-2.png
addTemplate.title=Add Colors Template
