header.title=Layout Template Profile
header.description=Select template to use for editor's layout
header.icon=/org/exbin/bined/jaguif/theme/resources/icons/48px/edit-guides.png
addTemplate.title=Add Layout Template
