header.title=Theme Template Profile
header.description=Select template options to use for editor's theme
header.icon=/org/exbin/bined/jaguif/theme/resources/icons/48px/thumbnail-2.png
addTemplate.title=Add Theme Template
