/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.bined.jaguif.component.gui;

import java.awt.Dimension;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.ParseException;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeListener;
import javax.swing.text.JTextComponent;
import org.exbin.bined.PositionCodeType;
import org.exbin.jaguif.App;
import org.exbin.jaguif.language.api.LanguageModuleApi;

/**
 * Spinner supporting multiple bases.
 */
@ParametersAreNonnullByDefault
public class BaseSwitchableSpinnerPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(BaseSwitchableSpinnerPanel.class);

    private final BaseSwitchableSpinnerEditor spinnerEditor;

    public BaseSwitchableSpinnerPanel() {
        initComponents();
        spinnerEditor = new BaseSwitchableSpinnerEditor(spinner);
        spinner.setEditor(spinnerEditor);
        init();
    }

    private void init() {
        // Spinner selection workaround from http://forums.sun.com/thread.jspa?threadID=409748&forumID=57
        spinnerEditor.addTextFieldFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (e.getSource() instanceof JTextComponent) {
                    final JTextComponent textComponent = (JTextComponent) e.getSource();
                    SwingUtilities.invokeLater(textComponent::selectAll);
                }
            }
        });

        Dimension preferredSize = baseSwitchButton.getPreferredSize();
        setPreferredSize(new Dimension(preferredSize.width * 4, preferredSize.height));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseSwitchPopupMenu = new javax.swing.JPopupMenu();
        octalMenuItem = new javax.swing.JMenuItem();
        decimalMenuItem = new javax.swing.JMenuItem();
        hexadecimalMenuItem = new javax.swing.JMenuItem();
        baseSwitchButton = new javax.swing.JButton();
        spinner = new javax.swing.JSpinner();

        octalMenuItem.setText(resourceBundle.getString("octalMenuItem.text")); // NOI18N
        octalMenuItem.setToolTipText(resourceBundle.getString("octalMenuItem.toolTipText")); // NOI18N
        octalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalMenuItemActionPerformed(evt);
            }
        });
        baseSwitchPopupMenu.add(octalMenuItem);

        decimalMenuItem.setText(resourceBundle.getString("decimalMenuItem.text")); // NOI18N
        decimalMenuItem.setToolTipText(resourceBundle.getString("decimalMenuItem.toolTipText")); // NOI18N
        decimalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalMenuItemActionPerformed(evt);
            }
        });
        baseSwitchPopupMenu.add(decimalMenuItem);

        hexadecimalMenuItem.setText(resourceBundle.getString("hexadecimalMenuItem.text")); // NOI18N
        hexadecimalMenuItem.setToolTipText(resourceBundle.getString("hexadecimalMenuItem.toolTipText")); // NOI18N
        hexadecimalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexadecimalMenuItemActionPerformed(evt);
            }
        });
        baseSwitchPopupMenu.add(hexadecimalMenuItem);

        setPreferredSize(new java.awt.Dimension(400, 300));

        baseSwitchButton.setText(resourceBundle.getString("codeType.decimal")); // NOI18N
        baseSwitchButton.setToolTipText(resourceBundle.getString("codeType.decimal.toolTipText")); // NOI18N
        baseSwitchButton.setComponentPopupMenu(baseSwitchPopupMenu);
        baseSwitchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseSwitchButtonActionPerformed(evt);
            }
        });

        spinner.setModel(new javax.swing.SpinnerNumberModel(0L, null, null, 1L));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(baseSwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinner))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spinner)
            .addComponent(baseSwitchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void baseSwitchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseSwitchButtonActionPerformed
        switch (spinnerEditor.getNumBase()) {
            case 8: {
                switchNumBase(PositionCodeType.DECIMAL);
                break;
            }
            case 10: {
                switchNumBase(PositionCodeType.HEXADECIMAL);
                break;
            }
            case 16: {
                switchNumBase(PositionCodeType.OCTAL);
                break;
            }
            default:
                throw new IllegalStateException();
        }
    }//GEN-LAST:event_baseSwitchButtonActionPerformed

    private void octalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalMenuItemActionPerformed
        switchNumBase(PositionCodeType.OCTAL);
    }//GEN-LAST:event_octalMenuItemActionPerformed

    private void decimalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalMenuItemActionPerformed
        switchNumBase(PositionCodeType.DECIMAL);
    }//GEN-LAST:event_decimalMenuItemActionPerformed

    private void hexadecimalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexadecimalMenuItemActionPerformed
        switchNumBase(PositionCodeType.HEXADECIMAL);
    }//GEN-LAST:event_hexadecimalMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baseSwitchButton;
    private javax.swing.JPopupMenu baseSwitchPopupMenu;
    private javax.swing.JMenuItem decimalMenuItem;
    private javax.swing.JMenuItem hexadecimalMenuItem;
    private javax.swing.JMenuItem octalMenuItem;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables

    private void switchNumBase(PositionCodeType codeType) {
        spinnerEditor.startAdjusting();
        long value = getValue();
        String codeTypeName = codeType.name().toLowerCase();
        baseSwitchButton.setText(resourceBundle.getString("codeType." + codeTypeName));
        baseSwitchButton.setToolTipText(resourceBundle.getString("codeType." + codeTypeName + ".toolTipText"));
        spinnerEditor.setNumBase(codeType.getBase());
        setValue(value);
        spinnerEditor.stopAdjusting();
    }

    public long getValue() {
        return (Long) spinner.getValue();
    }

    public void setValue(long value) {
        spinnerEditor.setPositionValue(value);
    }

    public void acceptInput() {
        try {
            spinner.commitEdit();
        } catch (ParseException ex) {
            // Ignore parse exception
        }
    }

    public void initFocus() {
        /* ((JSpinner.DefaultEditor) positionSpinner.getEditor()) */
        spinnerEditor.requestTextFieldFocusInWindow();
    }

    public void setMinimum(long minimum) {
        ((SpinnerNumberModel) spinner.getModel()).setMinimum(minimum);
    }

    public void setMaximum(long maximum) {
        ((SpinnerNumberModel) spinner.getModel()).setMaximum(maximum);
    }

    public void revalidateSpinner() {
        spinner.revalidate();
    }

    public void addChangeListener(ChangeListener changeListener) {
        spinner.addChangeListener(changeListener);
    }

    public void removeChangeListener(ChangeListener changeListener) {
        spinner.removeChangeListener(changeListener);
    }
}
