cursorPositionLabel.toolTipText=Cursor position
selectionFromLabel.toolTipText=Selection from
selectionToLabel.toolTipText=Selection to
caretPosition.text=%s to %s
codeType.octal=OCT
codeType.decimal=DEC
codeType.hexadecimal=HEX
