cursorPositionLabel.toolTipText=Cursor position
selectionFromLabel.toolTipText=Selection from
selectionToLabel.toolTipText=Selection to
codeType.octal=OCT
codeType.decimal=DEC
codeType.hexadecimal=HEX
