binarySearchFindAction.text=Find
binarySearchFindAction.shortDescription=Find words in text
binarySearchFindAction.smallIcon=/org/exbin/bined/jaguif/search/resources/icons/16px/edit-find.png
binarySearchFindAgainAction.text=Find Again
binarySearchFindAgainAction.shortDescription=Repeat the last search
binarySearchFindAgainAction.smallIcon=/org/exbin/bined/jaguif/search/resources/icons/16px/edit-find.png
binarySearchReplaceAction.text=Replace
binarySearchReplaceAction.shortDescription=Find and replace given string for another
binarySearchReplaceAction.smallIcon=/org/exbin/bined/jaguif/search/resources/icons/16px/edit-find-replace.png
