/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.bined.operation.gui;

import java.awt.Component;
import java.util.List;
import java.util.Optional;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.ParametersAreNonnullByDefault;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import org.exbin.framework.App;
import org.exbin.framework.language.api.LanguageModuleApi;
import org.exbin.framework.utils.WindowUtils;
import org.exbin.framework.bined.operation.api.DataOperationMethod;
import org.exbin.framework.utils.TestApplication;
import org.exbin.framework.utils.UtilsModule;

/**
 * Data operation panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class DataOperationPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(DataOperationPanel.class);

    private Controller controller;
    private DataOperationMethod activeMethod;
    private Component activeComponent;
    private Component previewComponent = null;

    public DataOperationPanel() {
        initComponents();
        init();
    }

    private void init() {
        optionsList.setModel(new DefaultListModel<>());
        optionsList.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, @Nullable Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (value == null) {
                    return super.getListCellRendererComponent(list, null, index, isSelected, cellHasFocus);
                }
                return super.getListCellRendererComponent(list, ((DataOperationMethod) value).getName(), index, isSelected, cellHasFocus);
            }
        });
        optionsList.addListSelectionListener((e) -> {
            activeMethod = optionsList.getSelectedValue();
            activeComponent = activeMethod != null ? activeMethod.createComponent() : null;
            if (controller != null) {
                controller.requestPreviewUpdate();
            }
            componentScrollPane.getViewport().setView(activeComponent);
            if (activeMethod != null) {
                try {
                    activeMethod.initFocus(activeComponent);
                } catch (Throwable ex) {
                    Logger.getLogger(DataOperationPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }

    public void setDataMethods(List<? extends DataOperationMethod> dataMethods) {
        DefaultListModel<DataOperationMethod> listModel = (DefaultListModel<DataOperationMethod>) optionsList.getModel();
        for (DataOperationMethod dataMethod : dataMethods) {
            listModel.addElement(dataMethod);
        }
    }

    @Nonnull
    public Optional<DataOperationMethod> getActiveMethod() {
        return Optional.ofNullable(activeMethod);
    }

    @Nonnull
    public Optional<Component> getActiveComponent() {
        return Optional.ofNullable(activeComponent);
    }

    public void setPreviewComponent(Component previewComponent) {
        if (this.previewComponent != null) {
            previewPanel.remove(this.previewComponent);
        }

        this.previewComponent = previewComponent;
        previewPanel.add(previewComponent);
        previewPanel.revalidate();
        previewPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        methodLabel = new javax.swing.JLabel();
        optionsScrollPane = new javax.swing.JScrollPane();
        optionsList = new javax.swing.JList<>();
        splitPane = new javax.swing.JSplitPane();
        componentScrollPane = new javax.swing.JScrollPane();
        previewPanel = new javax.swing.JPanel();

        methodLabel.setText(resourceBundle.getString("methodLabel.text")); // NOI18N

        optionsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        optionsScrollPane.setViewportView(optionsList);

        splitPane.setDividerLocation(400);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setLeftComponent(componentScrollPane);

        previewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceBundle.getString("previewPanel.border.title"))); // NOI18N
        previewPanel.setLayout(new javax.swing.BoxLayout(previewPanel, javax.swing.BoxLayout.X_AXIS));
        splitPane.setBottomComponent(previewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(methodLabel)
                    .addComponent(optionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(methodLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsScrollPane)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void initFocus() {
        // TODO
    }

    public void selectActiveMethod(@Nullable DataOperationMethod method) {
        DefaultListModel<DataOperationMethod> listModel = (DefaultListModel<DataOperationMethod>) optionsList.getModel();
        if (method == null && !listModel.isEmpty()) {
            optionsList.setSelectedIndex(0);
        } else {
            int methodIndex = listModel.indexOf(method);
            if (methodIndex >= 0) {
                optionsList.setSelectedIndex(methodIndex);
            }
        }
    }

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        TestApplication testApplication = UtilsModule.createTestApplication();
        testApplication.launch(() -> {
            testApplication.addModule(org.exbin.framework.language.api.LanguageModuleApi.MODULE_ID, new org.exbin.framework.language.api.utils.TestLanguageModule());
            WindowUtils.invokeWindow(new DataOperationPanel());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane componentScrollPane;
    private javax.swing.JLabel methodLabel;
    private javax.swing.JList<org.exbin.framework.bined.operation.api.DataOperationMethod> optionsList;
    private javax.swing.JScrollPane optionsScrollPane;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    public interface Controller {

        void requestPreviewUpdate();
    }
}
