/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.bined.blockedit.component.gui;

import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import org.exbin.bined.CodeAreaUtils;
import org.exbin.framework.utils.LanguageUtils;
import org.exbin.framework.utils.WindowUtils;

/**
 * Random data component panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class RandomDataPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(RandomDataPanel.class);

    public RandomDataPanel() {
        initComponents();
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        sizeLabel = new javax.swing.JLabel();
        sizeBaseSwitchableSpinnerPanel = new org.exbin.framework.bined.gui.BaseSwitchableSpinnerPanel();
        randomDataLabel = new javax.swing.JLabel();
        fullBytesRadioButton = new javax.swing.JRadioButton();
        lowerHalfRadioButton = new javax.swing.JRadioButton();
        alphabetOnlyRadioButton = new javax.swing.JRadioButton();
        numberDigitsRadioButton = new javax.swing.JRadioButton();

        sizeLabel.setText(resourceBundle.getString("sizeLabel.text")); // NOI18N

        randomDataLabel.setText(resourceBundle.getString("randomDataLabel.text")); // NOI18N

        buttonGroup.add(fullBytesRadioButton);
        fullBytesRadioButton.setSelected(true);
        fullBytesRadioButton.setText(resourceBundle.getString("fullBytesRadioButton.text")); // NOI18N

        buttonGroup.add(lowerHalfRadioButton);
        lowerHalfRadioButton.setText(resourceBundle.getString("lowerHalfRadioButton.text")); // NOI18N

        buttonGroup.add(alphabetOnlyRadioButton);
        alphabetOnlyRadioButton.setText(resourceBundle.getString("alphabetOnlyRadioButton.text")); // NOI18N

        buttonGroup.add(numberDigitsRadioButton);
        numberDigitsRadioButton.setText(resourceBundle.getString("numberDigitsRadioButton.text")); // NOI18N
        numberDigitsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberDigitsRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeBaseSwitchableSpinnerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                    .addComponent(lowerHalfRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullBytesRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sizeLabel)
                            .addComponent(randomDataLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(alphabetOnlyRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberDigitsRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sizeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeBaseSwitchableSpinnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randomDataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullBytesRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerHalfRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alphabetOnlyRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberDigitsRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numberDigitsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberDigitsRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberDigitsRadioButtonActionPerformed

    @Nonnull
    public AlgorithmType getAlgorithmType() {
        if (lowerHalfRadioButton.isSelected()) {
            return AlgorithmType.LOWER_HALF;
        } else if (alphabetOnlyRadioButton.isSelected()) {
            return AlgorithmType.ALPHABET_ONLY;
        } else if (numberDigitsRadioButton.isSelected()) {
            return AlgorithmType.NUMBER_DIGITS;
        }

        return AlgorithmType.FULL_BYTES;
    }

    public void setFillWith(AlgorithmType algorithm) {
        switch (algorithm) {
            case FULL_BYTES: {
                fullBytesRadioButton.setSelected(true);
                break;
            }
            case LOWER_HALF: {
                lowerHalfRadioButton.setSelected(true);
                break;
            }
            case ALPHABET_ONLY: {
                alphabetOnlyRadioButton.setSelected(true);
                break;
            }
            case NUMBER_DIGITS: {
                numberDigitsRadioButton.setSelected(true);
                break;
            }
            default:
                throw CodeAreaUtils.getInvalidTypeException(algorithm);
        }
    }

    public long getDataLength() {
        return sizeBaseSwitchableSpinnerPanel.getValue();
    }

    public void setDataLength(long dataLength) {
        sizeBaseSwitchableSpinnerPanel.setValue(dataLength);
    }

    public void initFocus() {
        sizeBaseSwitchableSpinnerPanel.initFocus();
    }

    public void acceptInput() {
        sizeBaseSwitchableSpinnerPanel.acceptInput();
    }

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        WindowUtils.invokeDialog(new RandomDataPanel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alphabetOnlyRadioButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton fullBytesRadioButton;
    private javax.swing.JRadioButton lowerHalfRadioButton;
    private javax.swing.JRadioButton numberDigitsRadioButton;
    private javax.swing.JLabel randomDataLabel;
    private org.exbin.framework.bined.gui.BaseSwitchableSpinnerPanel sizeBaseSwitchableSpinnerPanel;
    private javax.swing.JLabel sizeLabel;
    // End of variables declaration//GEN-END:variables

    public enum AlgorithmType {
        FULL_BYTES,
        LOWER_HALF,
        ALPHABET_ONLY,
        NUMBER_DIGITS
    }
}
