zoomInAction.text=Zoom In
zoomInAction.shortDescription=Increase font size
zoomOutAction.text=Zoom Out
zoomOutAction.shortDescription=Decrease font size
resetFontSizeAction.text=Reset Font Size
resetFontSizeAction.shortDescription=Reset font size to default (12)
viewFontSubMenu.name=Font
