cursorPositionLabel.toolTipText=Cursor position
selectionFromLabel.toolTipText=Selection from
selectionToLabel.toolTipText=Selection to
selectionLengthLabel.toolTipText=Selection length
octalCursorPositionModeRadioButtonMenuItem.text=Show as octal
decimalCursorPositionModeRadioButtonMenuItem.text=Show as decimal
hexadecimalCursorPositionModeRadioButtonMenuItem.text=Show as hexadecimal
cursorPositionShowOffsetCheckBoxMenuItem.text=Show offset
cursorPositionCodeTypeMenu.text=Code Type
caretPosition.text=%s to %s
codeType.octal=OCT
codeType.decimal=DEC
codeType.hexadecimal=HEX
