selectionFromLabel.toolTipText=Selection from
selectionToLabel.toolTipText=Selection to
documentSizeLabel.toolTipText=Document size
selectionLengthLabel.toolTipText=Selection length
documentSizeCopyMenuItem.text=Copy
octDocumentSizeModeMenuItem.text=Show as octal
decDocumentSizeModeMenuItem.text=Show as decimal
hexDocumentSizeModeMenuItem.text=Show as hexadecimal
octDocumentSizeModeRadioButtonMenuItem.text=Show as octal
decDocumentSizeModeRadioButtonMenuItem.text=Show as decimal
hexadecimalDocumentSizeModeRadioButtonMenuItem.text=Show as hexadecimal
caretPosition.text=%s to %s
documentSize.text=%s of %s
codeType.octal=OCT
codeType.decimal=DEC
codeType.hexadecimal=HEX
