/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.framework.bined.operation.method.gui;

import java.util.ResourceBundle;
import javax.annotation.Nonnull;
import javax.annotation.ParametersAreNonnullByDefault;
import org.exbin.framework.App;
import org.exbin.framework.bined.operation.method.Base64DataMethod;
import org.exbin.framework.language.api.LanguageModuleApi;
import org.exbin.framework.utils.TestApplication;
import org.exbin.framework.utils.UtilsModule;
import org.exbin.framework.utils.WindowUtils;

/**
 * Base 64 data component panel.
 *
 * @author ExBin Project (https://exbin.org)
 */
@ParametersAreNonnullByDefault
public class Base64DataPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(Base64DataPanel.class);

    private ModeChangeListener modeChangeListener = null;

    public Base64DataPanel() {
        initComponents();
        init();
    }

    private void init() {
    }

    @Nonnull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        splitPane = new javax.swing.JSplitPane();
        typePanel = new javax.swing.JPanel();
        operationTypeLabel = new javax.swing.JLabel();
        basicEncoderRadioButton = new javax.swing.JRadioButton();
        basicDecoderRadioButton = new javax.swing.JRadioButton();
        mimeEncoderRadioButton = new javax.swing.JRadioButton();
        mimeDecoderRadioButton = new javax.swing.JRadioButton();
        urlEncoderRadioButton = new javax.swing.JRadioButton();
        urlDecoderRadioButton = new javax.swing.JRadioButton();
        parametersPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        operationTypeLabel.setText(resourceBundle.getString("operationTypeLabel.text")); // NOI18N

        buttonGroup.add(basicEncoderRadioButton);
        basicEncoderRadioButton.setSelected(true);
        basicEncoderRadioButton.setText(resourceBundle.getString("basicEncoderRadioButton.text")); // NOI18N
        basicEncoderRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                basicEncoderRadioButtonItemStateChanged(evt);
            }
        });

        buttonGroup.add(basicDecoderRadioButton);
        basicDecoderRadioButton.setText(resourceBundle.getString("basicDecoderRadioButton.text")); // NOI18N
        basicDecoderRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                basicDecoderRadioButtonItemStateChanged(evt);
            }
        });

        buttonGroup.add(mimeEncoderRadioButton);
        mimeEncoderRadioButton.setText(resourceBundle.getString("mimeEncoderRadioButton.text")); // NOI18N
        mimeEncoderRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mimeEncoderRadioButtonItemStateChanged(evt);
            }
        });

        buttonGroup.add(mimeDecoderRadioButton);
        mimeDecoderRadioButton.setText(resourceBundle.getString("mimeDecoderRadioButton.text")); // NOI18N
        mimeDecoderRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mimeDecoderRadioButtonItemStateChanged(evt);
            }
        });

        buttonGroup.add(urlEncoderRadioButton);
        urlEncoderRadioButton.setText(resourceBundle.getString("urlEncoderRadioButton.text")); // NOI18N
        urlEncoderRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                urlEncoderRadioButtonItemStateChanged(evt);
            }
        });

        buttonGroup.add(urlDecoderRadioButton);
        urlDecoderRadioButton.setText(resourceBundle.getString("urlDecoderRadioButton.text")); // NOI18N
        urlDecoderRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                urlDecoderRadioButtonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout typePanelLayout = new javax.swing.GroupLayout(typePanel);
        typePanel.setLayout(typePanelLayout);
        typePanelLayout.setHorizontalGroup(
            typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(basicEncoderRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(typePanelLayout.createSequentialGroup()
                        .addComponent(operationTypeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mimeDecoderRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicDecoderRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mimeEncoderRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(urlEncoderRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(urlDecoderRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        typePanelLayout.setVerticalGroup(
            typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operationTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicEncoderRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basicDecoderRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mimeEncoderRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mimeDecoderRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlEncoderRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlDecoderRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(typePanel);

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(parametersPanel);

        add(splitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void basicEncoderRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_basicEncoderRadioButtonItemStateChanged
        modeChanged();
    }//GEN-LAST:event_basicEncoderRadioButtonItemStateChanged

    private void basicDecoderRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_basicDecoderRadioButtonItemStateChanged
        modeChanged();
    }//GEN-LAST:event_basicDecoderRadioButtonItemStateChanged

    private void mimeEncoderRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mimeEncoderRadioButtonItemStateChanged
        modeChanged();
    }//GEN-LAST:event_mimeEncoderRadioButtonItemStateChanged

    private void mimeDecoderRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mimeDecoderRadioButtonItemStateChanged
        modeChanged();
    }//GEN-LAST:event_mimeDecoderRadioButtonItemStateChanged

    private void urlEncoderRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_urlEncoderRadioButtonItemStateChanged
        modeChanged();
    }//GEN-LAST:event_urlEncoderRadioButtonItemStateChanged

    private void urlDecoderRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_urlDecoderRadioButtonItemStateChanged
        modeChanged();
    }//GEN-LAST:event_urlDecoderRadioButtonItemStateChanged

    private void modeChanged() {
        if (modeChangeListener != null) {
            modeChangeListener.modeChanged();
        }
    }

    @Nonnull
    public Base64DataMethod.OperationType getOperationType() {
        return basicDecoderRadioButton.isSelected() ? Base64DataMethod.OperationType.BASIC_DECODER : Base64DataMethod.OperationType.BASIC_ENCODER;
    }

    public void setOperationType(Base64DataMethod.OperationType operationType) {
        switch (operationType) {
            case BASIC_DECODER:
                basicDecoderRadioButton.setSelected(true);
                break;
            case BASIC_ENCODER:
                basicEncoderRadioButton.setSelected(true);
                break;
            case MIME_DECODER:
                mimeDecoderRadioButton.setSelected(true);
                break;
            case MIME_ENCODER:
                mimeEncoderRadioButton.setSelected(true);
                break;
            case URL_DECODER:
                urlDecoderRadioButton.setSelected(true);
                break;
            case URL_ENCODER:
                urlEncoderRadioButton.setSelected(true);
                break;
            default:
                throw new IllegalStateException();
        }
    }

    public void setModeChangeListener(ModeChangeListener modeChangeListener) {
        this.modeChangeListener = modeChangeListener;
    }

    public void initFocus() {
        basicEncoderRadioButton.requestFocus();
    }

    public void acceptInput() {
    }

    /**
     * Test method for this panel.
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        TestApplication testApplication = UtilsModule.createTestApplication();
        testApplication.launch(() -> {
            testApplication.addModule(org.exbin.framework.language.api.LanguageModuleApi.MODULE_ID, new org.exbin.framework.language.api.utils.TestLanguageModule());
            WindowUtils.invokeWindow(new Base64DataPanel());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton basicDecoderRadioButton;
    private javax.swing.JRadioButton basicEncoderRadioButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton mimeDecoderRadioButton;
    private javax.swing.JRadioButton mimeEncoderRadioButton;
    private javax.swing.JLabel operationTypeLabel;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel typePanel;
    private javax.swing.JRadioButton urlDecoderRadioButton;
    private javax.swing.JRadioButton urlEncoderRadioButton;
    // End of variables declaration//GEN-END:variables

    public interface ModeChangeListener {

        void modeChanged();
    }
}
